media:
  input: static/assets/images/
  output: /assets/images/
  extensions: [ jpg, jpeg, png, webp, gif, svg ]

content:
  - name: general
    label: General
    type: file
    format: yaml
    path: hugo.yaml
    icon: file-cog
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: params.profileMode.title
        lable: Titel
        type: string
      - name: params.profileMode.enabled
        label: "Profile Mode"
        type: boolean
      - name: params.profileMode.subtitle
        label: "subtitle"
        type: string
      - name: params.profileMode.imageUrl
        label: picture
        type: image
        list: false
        options:
          path: /assets/images/
          extensions: [ jpg, jpeg, png, webp, gif, svg ]

  - name: posts
    label: Posts
    type: collection
    path: content/posts
    icon: book-check
    filename: 'fields.title.md'
    view:
      fields:
        - title
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: "false"
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Page content
        type: rich-text
        options:
          format: markdown
          image:
            input: static/assets/images
            output: /assets/images/
            path: static/assets/images
            extensions: [ jpg, jpeg, png, webp, gif, svg ]
        required: false